# Generated by Django 3.1 on 2020-08-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=11)),
                ('send_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'verifycode',
            },
        ),
    ]
