# Generated by Django 3.1 on 2020-08-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200811_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifycode',
            old_name='phone',
            new_name='mobile',
        ),
    ]
