# Generated by Django 3.1 on 2020-08-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200811_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2020-02-02'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('boy', '男'), ('girl', '女')], default='boy', max_length=4),
        ),
    ]
